// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public enum SupportedCurrency: String, EnumType {
  case aed = "aed"
  case ars = "ars"
  case aud = "aud"
  case bdt = "bdt"
  case bhd = "bhd"
  case bmd = "bmd"
  case brl = "brl"
  case cad = "cad"
  case chf = "chf"
  case clp = "clp"
  case cny = "cny"
  case czk = "czk"
  case dkk = "dkk"
  case eur = "eur"
  case gbp = "gbp"
  case hkd = "hkd"
  case huf = "huf"
  case idr = "idr"
  case ils = "ils"
  case inr = "inr"
  case jpy = "jpy"
  case krw = "krw"
  case kwd = "kwd"
  case lkr = "lkr"
  case mmk = "mmk"
  case mxn = "mxn"
  case myr = "myr"
  case ngn = "ngn"
  case nok = "nok"
  case nzd = "nzd"
  case php = "php"
  case pkr = "pkr"
  case pln = "pln"
  case rub = "rub"
  case sar = "sar"
  case sek = "sek"
  case sgd = "sgd"
  case thb = "thb"
  case `try` = "try"
  case twd = "twd"
  case uah = "uah"
  case usd = "usd"
  case vef = "vef"
  case vnd = "vnd"
  case xdr = "xdr"
  case zar = "zar"
}
